name: Docker Build

on:
  # push:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  # extract pr metadata
  extract-pr-metadata:
    runs-on: ubuntu-latest
    outputs:
      pr-merged-commit-sha: ${{ steps.commit-sha.outputs.pr-merged-commit-sha }}
    steps:
      - name: get-commit-sha
        id: commit-sha
        run: |
          SHA_OUTPUT=$(echo "${{ github.event.pull_request.merge_commit_sha }} | cut -c 1-7")
          echo "pr-merged-commit-sha=$SHA_OUTPUT >> $GITHUB_OUTPUT"

  docker-image-build:
    # if: github.event.pull_request.merged == true
    needs: [extract-pr-metadata]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t counter-app-docker/microservice-counter-app:${{ needs.extract-pr-metadata.outputs.pr-merged-commit-sha }} .
          # docker tag counter-app-docker/microservice-counter-app:${{ github.event.pull_request.merge_commit_sha }} counter-app-docker/microservice-counter-app:latest
          # docker push counter-app-docker/microservice-counter-app:latest

  # Optional: Push to Docker registry
  # - name: Login to Docker Hub
  #   uses: docker/login-action@v2
  #   with:
  #     username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     password: ${{ secrets.DOCKERHUB_TOKEN }}

  # - name: Push to Docker Hub
  #   uses: docker/build-push-action@v4
  #   with:
  #     context: .
  #     push: true
  #     tags: counter-app-docker/my-app:latest
